Update user guide
AY2324S1-CS2103T-W10-3/tp pull request #114
Opened 2023-10-25 17:19 UTC by techjay-c

2023-10-25 18:20 UTC, ruth-lim requested changes

2023-10-25 18:20 UTC, ruth-lim commented on docs/UserGuide.md
> +**Format:** `delete-dentist DENTIST_ID`
Format is repeated twice in this section

2023-10-25 18:20 UTC, ruth-lim commented on docs/UserGuide.md
> +### Searches for a dentist by Dentist ID or keyword: `search-dentist`
Standardise the verb form with other commands? Are we going with -ing/ -s?

2023-10-25 18:20 UTC, ruth-lim commented on docs/UserGuide.md
> +one result that matches your search criteria.** This is helpful when:
Is there extra ** here?

2023-10-25 18:20 UTC, ruth-lim commented on docs/UserGuide.md
>  ## Part 2 - Patient Features
1. Under Examples: command should be in lower caps `add-patient`
2. Can double check the order of the parameters for the format of `add-patient`? I think we should standardise with the order we give in the example.

2023-10-25 18:20 UTC, ruth-lim commented on docs/UserGuide.md
> +one result that matches your search criteria.** This is helpful when:
Extra ** here?

2023-10-25 18:20 UTC, ruth-lim commented on docs/UserGuide.md
> +| **Search Dentist by Name**              | `search-dentist NAME` <br> e.g., `search-dentist Tom`
Change to Search Dentist by Keyword?

2023-10-25 18:20 UTC, ruth-lim commented on docs/UserGuide.md
> +| **Search Patient by Name**              | `search-patient NAME` <br> e.g., `search-patient John`
Change to Search Patient by Keyword?

2023-10-26 01:59 UTC, SynapseProgramming approved these changes
approved.

2023-10-26 02:07 UTC, ruth-lim approved these changes
LGTM

2023-10-26 02:08 UTC, merged